site_name: raspiCamSrv V4.7.x Documentation
plugins:
    - search
    - mike
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - content.code.copy

not_in_nav: |
  Z_Legacy*.md

nav:
  - Home: index.md
  - Getting Started: 
      - Overview: getting_started_overview.md
      - Requirements: requirements.md
      - System Setup: system_setup.md
      - Installation: installation.md
      - Alternatives:
          - Manual Step by Step Installation: installation_man.md
          - Service Configuration: service_configuration.md
          - Running raspiCamSrv as Docker container: SetupDocker.md
          - Setup of Raspberry Pi Zero as Standalone System: bp_PiZero_Standalone.md
          - Configuring as Hotspot:
              - Hotspot Setup for Trixie: bp_Hotspot_Trixie.md
              - Hotspot Setup for Boookworm: bp_Hotspot_Bookworm.md
              - Hotspot Setup for Bullseye: bp_Hotspot_Bullseye.md
      - Trouble Shooting Guide: Troubelshooting.md
  - Features: features.md
  - References:
      - Picamera2 Manual: picamera2_manual.md
  - Releases:
      - Release Notes: ReleaseNotes.md
      - Updating a raspiCamSrv Installation: updating_raspiCamSrv.md
  - User Guide:
      - Overview: UserGuide.md
      - Authentication: Authentication.md
      - Live Menu:
          - Live Screen: LiveScreen.md
          - Camera Controls:
               - Overview: CameraControls.md
               - Focus Handling: FocusHandling.md
               - Zoom/Pan/Tilt: ZoomPan.md
               - Auto-Exposure: CameraControls_AutoExposure.md
               - Exposure: CameraControls_Exposure.md
               - Image: CameraControls_Image.md
               - Camera Controls for USB Cameras: CameraControls_UsbCams.md
               - Cropping: ScalerCrop.md
          - Direct Control Panel: LiveDirectControl.md
      - Photo / Video Taking: Phototaking.md
      - Config Menu:
          - raspiCamSrv Camera Configuration: Configuration.md
          - raspiCamSrv Camera AI Configuration: Configuration_AI.md
          - Tuning: Tuning.md
      - Info Menu:
          - Overview: Information.md
          - System Information: Information_Sys.md
          - Installed Cameras: Information_Cam.md
          - Active Camera Properties: Information_CamPrp.md
          - Active Camera Sensor Modes: Information_Sensor.md
      - Photos Menu:
          - Photo Viewer: PhotoViewer.md
      - Photo Series Menu:
          - Photo Series: PhotoSeries.md
          - Timelapse Series: PhotoSeriesTimelapse.md
          - Exposure Series: PhotoSeriesExp.md
          - Focus Stack Series: PhotoSeriesFocus.md
      - Trigger Menu:
          - Overview: Trigger.md
          - Trigger Configuration: TriggerTriggers.md
          - Action Configuration: TriggerActions.md
          - Trigger/Action Configuration: TriggerTriggerActions.md
          - Motion Detection Configuration: TriggerMotion.md
          - Camera Action Configuration: TriggerCameraActions.md
          - Notification Configuration: TriggerNotification.md
          - Active Motion Capturing: TriggerActive.md
          - Event Viewer and Calendar: TriggerEventViewer.md
      - Cam Menu:
          - Overview: Cam.md
          - Web Cam Dialog: CamWebcam.md
          - Multi-Cam Dialog: CamMulticam.md
          - Camera Calibration Dialog: CamCalibration.md
          - Stereo Camera Dialog: CamStereo.md
      - Console Menu:
          - Overview: Console.md
          - Versatile Buttons: ConsoleVButtons.md
          - Action Buttons: ConsoleActionButtons.md
      - Settings Menu:
          - Settings Parameters: Settings.md
          - Configuration Management: SettingsConfiguration.md
          - User Management: SettingsUsers.md
          - API Settings: SettingsAPI.md
          - Settings for Versatile Buttons: SettingsVButtons.md
          - Settings for Action Buttons: SettingsAButtons.md
          - GPIO Device Configuration: SettingsDevices.md
          - GPIO Devices:
              - Stepper Motor: gpioDevices/StepperMotor.md
          - Update: SettingsUpdate.md
      - AI Camera Support: AiCameraSupport.md
      - Background Processes: Background Processes.md
  - No Camera Mode:
      - User Guide: UserGuide_NoCam.md
      - System Information: Information_Sys.md
      - Settings: Settings_NoCam.md
      - Configuration Management: SettingsConfiguration_NoCam.md

  - API: API.md




